"use client";
import React, { createContext, useContext, useState } from 'react';

const dictionary = {
  es: {
    nav: { 
      dashboard: 'Dashboard',
      vehiculos: 'Vehículos', 
      reservas: 'Reservas', 
      clientes: 'Clientes', 
      reportes: 'Reportes', 
      taller: 'Taller', 
      tarifas: 'Tarifas',
      calendario: 'Calendario',
      notificaciones: 'Notificaciones',
      asistente: 'Asistente IA',
      superadmin: 'Super Admin'
    },
    header: { search: 'Buscar placa...', ticket: 'ABRIR NUEVO TICKET' },
    home: { title: 'Gestión de Flota', subtitle: 'Administración y control de inventario' },
    card: { km: 'Kilometraje', maint: 'Mantenimiento', btn_details: 'Detalles' },
    status: { available: 'Disponible', maintenance: 'En Taller', rented: 'Alquilado' },
    a11y: { dark: 'Modo Oscuro 🌙', light: 'Modo Claro ☀️' },
    analytics: {
      title: 'Dashboard Analitico',
      subtitle: 'ROI, ocupacion y rendimiento de flota',
      ingresosMes: 'Ingresos del mes',
      ingresosMesAnterior: 'Ingresos mes anterior',
      roi: 'ROI estimado',
      roiHelper: 'Estimado sobre inversion de flota',
      ocupacion: 'Ocupacion de flota',
      ocupacionHelper: 'vehiculos en total',
      clientesRegistrados: 'Clientes registrados',
      ingresos12m: 'Ingresos mensuales (12 meses)',
      ingresosChartAria: 'Grafico de barras de ingresos mensuales de los ultimos doce meses',
      estadoFlota: 'Estado de flota',
      estadoFlotaChartAria: 'Grafico circular de distribucion del estado de la flota',
      estadoFlotaHelper: 'Distribucion entre disponibles, rentados y mantenimiento',
      topRentables: 'Top vehiculos mas rentables',
      gananciaEstimada: 'ganancia estimada',
    },
    assistantIA: {
      title: 'Asistente IA de Flota',
      subtitle: 'Recomendaciones inteligentes para tu negocio',
      demoMode: 'Modo Demo - IA conectada en Ciclo 2',
      quickBuy: '¿Qué moto debería comprar?',
      quickMaint: '¿Cuándo hacer mantenimiento?',
      quickPrices: 'Analiza mis precios',
      quickRates: 'Estrategia de tarifas',
      emptyHello: 'Hola! Soy tu asistente de IA.',
      emptyHint: 'Preguntame sobre tu flota, mantenimiento o estrategias de precios.',
      placeholder: 'Escribe tu pregunta aqui...',
      send: 'Enviar',
      respComprar: 'Basandome en el analisis de tu flota actual, te recomiendo adquirir motos de tipo Adventure o Naked, ya que tienen la mayor tasa de ocupacion (85%). Considera modelos como la BMW G310 GS o Yamaha MT-03, que son populares entre tus clientes y tienen bajo costo de mantenimiento.',
      respAdquirir: 'Para expandir tu flota, sugiero enfocarte en vehiculos de gama media (precio $45-60/dia). Estos tienen el mejor balance entre demanda y rentabilidad segun tus datos historicos.',
      respMantenimiento: 'Segun el kilometraje promedio de tu flota (12,500 km), recomiendo programar mantenimientos preventivos cada 2,500 km. Actualmente tienes 2 vehiculos cerca del limite que deberian ingresar a taller en los proximos 7 dias.',
      respPrecio: 'Analizando tu ocupacion actual del 65%, sugiero incrementar precios en un 15% durante fines de semana y mantener descuentos del 10% para alquileres de +7 dias. Esto podria aumentar tus ingresos mensuales en aproximadamente $2,400.',
      respTarifa: 'Tu estrategia de tarifas actual es solida. Sin embargo, podrias implementar precios dinamicos para temporada alta (Diciembre-Enero y Semana Santa) con incrementos del 25-30%. Esto es comun en el mercado colombiano.',
      respDefault: 'He analizado los datos de tu negocio. Tu flota tiene una tasa de ocupacion del 65%, con ingresos promedio de $8,500/mes. Los vehiculos tipo Naked son los mas rentables. ¿Te gustaria que profundice en algun aspecto especifico como expansion, mantenimiento o estrategia de precios?',
    },
    reservas: {
      title: 'Motor de Reservas',
      subtitle: 'Gestion de disponibilidad y facturacion',
      checkinShortcut: 'Check-in / Check-out',
      periodoTitle: '1. Periodo de Renta',
      fechaRetiro: 'Fecha Retiro',
      fechaDevolucion: 'Fecha Devolucion',
      diasTotales: 'Dias Totales',
      tarifasTitle: '2. Tarifas y Adicionales',
      precioPorDia: 'Precio por dia',
      precioFijo: 'Precio Fijo',
      sinTarifas: 'No hay tarifas extras configuradas',
      crearCargo: 'Crear Nuevo Cargo',
      nombre: 'Nombre',
      cobrarPorDia: 'Cobrar por dia',
      agregar: 'Agregar +',
      vehiculosDisponibles: 'Vehiculos Disponibles',
      rango: 'Rango',
      sinDisponibilidad: 'Sin disponibilidad en estas fechas',
      sinDisponibilidadHint: 'Intenta cambiar el rango o verifica si las motos estan en mantenimiento.',
      seleccionada: 'Seleccionada',
      confirmarRenta: 'Confirmar Renta',
      ticketReserva: 'Ticket de Reserva',
      periodo: 'Periodo',
      buscarCliente: 'Buscar cliente',
      buscarClientePlaceholder: 'Nombre o documento',
      clienteSistema: 'Cliente del sistema',
      seleccionarCliente: 'Seleccionar cliente',
      licencia: 'Licencia',
      vencimiento: 'Vencimiento',
      licenciaValida: 'Licencia valida para la reserva',
      licenciaInvalida: 'Licencia vencida o invalida para la fecha seleccionada',
      metodoPago: 'Metodo de pago',
      efectivo: 'Efectivo',
      tarjetaCredito: 'Tarjeta credito',
      tarjetaDebito: 'Tarjeta debito',
      transferencia: 'Transferencia',
      billetera: 'Billetera digital',
      concepto: 'Concepto',
      subtotal: 'Subtotal',
      rentaXDias: 'Renta x dias',
      deposito: 'Deposito requerido',
      totalPagar: 'Total a pagar',
      cancelar: 'Cancelar',
      confirmarReserva: 'Confirmar Reserva',
      errorSeleccionVehiculo: 'Selecciona un vehiculo para continuar.',
      errorSeleccionCliente: 'Selecciona un cliente existente para crear la reserva.',
      errorLicencia: 'La licencia del cliente no es valida para la fecha de inicio.',
      errorSolapamiento: 'El vehiculo ya tiene una reserva en ese rango de fechas.',
      successReserva: 'Reserva creada correctamente.',
    },
    calendarioHu: {
      title: 'Calendario de Ocupación',
      subtitle: 'Vista semanal para coordinar entregas y devoluciones',
      nuevaReserva: '+ Nueva reserva',
      tipo: 'Tipo',
      estado: 'Estado',
      todos: 'Todos',
      disponible: 'Disponible',
      rentado: 'Rentado',
      mantenimiento: 'Mantenimiento',
      semanaAnterior: 'Semana anterior',
      semanaSiguiente: 'Semana siguiente',
      vehiculo: 'Vehiculo',
      sinReservas: 'Sin reservas',
      libre: 'Libre',
      sinVehiculos: 'No hay vehiculos con esos filtros.',
      detalleLabel: 'Detalle de ocupación',
      detalleTitle: 'Detalle de ocupación',
      cerrar: 'Cerrar',
      documento: 'Documento',
      periodo: 'Periodo',
    },
    checkin: {
      title: 'Check-in / Check-out',
      subtitle: 'Registro fisico del estado del vehiculo',
      volverReservas: 'Volver a reservas',
      reserva: 'Reserva',
      seleccionar: 'Seleccionar',
      tipoRegistro: 'Tipo de registro',
      vehiculo: 'Vehiculo',
      sinSeleccionar: 'Sin seleccionar',
      kilometraje: 'Kilometraje',
      combustible: 'Combustible (%)',
      checklist: 'Checklist de estado',
      fotos: 'Fotos (URLs separadas por coma)',
      observaciones: 'Observaciones',
      guardar: 'Guardar',
      historial: 'Historial de inspecciones',
      sinInspecciones: 'Aun no hay inspecciones registradas.',
      errorReserva: 'Selecciona una reserva valida para continuar.',
      successGuardado: 'Registro guardado correctamente.',
      errorGuardado: 'No se pudo guardar la inspeccion.',
      kmAbbr: 'KM',
      combustibleAbbr: 'Combustible',
    },
    clientesHu: {
      title: 'Base de Datos de Clientes',
      subtitle: 'Gestion de informacion y perfiles',
      nuevo: '+ Nuevo Cliente',
      buscarPlaceholder: 'Buscar por nombre, documento, telefono o email...',
      tablaCaption: 'Lista de clientes registrados',
      cliente: 'Cliente',
      documento: 'Documento',
      contacto: 'Contacto',
      reservas: 'Reservas',
      score: 'Score',
      clasificacion: 'Clasificacion',
      acciones: 'Acciones',
      ver: 'Ver',
      editar: 'Editar',
      modalEditar: 'Editar Cliente',
      modalNuevo: 'Nuevo Cliente',
      nombreCompleto: 'Nombre Completo',
      email: 'Email',
      tipoDocumento: 'Tipo Documento',
      numeroDocumento: 'Número Documento',
      telefono: 'Telefono',
      fechaNacimiento: 'Fecha de Nacimiento',
      direccion: 'Direccion',
      licenciaNumero: 'Licencia Numero',
      categoria: 'Categoria',
      vencimiento: 'Vencimiento',
      cancelar: 'Cancelar',
      actualizar: 'Actualizar',
      crear: 'Crear',
      successActualizado: 'Cliente actualizado exitosamente',
      successCreado: 'Cliente creado exitosamente',
      errorGuardar: 'No se pudo guardar el cliente',
      frecuente: 'FRECUENTE',
      riesgo: 'RIESGO',
      nuevoLabel: 'NUEVO',
      regular: 'REGULAR',
    },
    clienteDetalle: {
      notFound: 'Cliente no encontrado',
      volverListado: 'Volver al listado',
      ficha: 'Ficha del Cliente',
      volver: 'Volver',
      riesgoTitle: 'Riesgo alto detectado',
      riesgoDesc: 'El cliente tiene incidentes/multas recientes. Revisa condiciones antes de confirmar una nueva reserva.',
      ltv: 'LTV',
      reservasTotales: 'Reservas Totales',
      reservasActivas: 'Reservas Activas',
      multasDanos: 'Multas/Daños',
      topVehiculos: 'Vehículos más rentados',
      sinHistorico: 'No hay historico de reservas.',
      incidentesTitle: 'Incidentes y multas',
      tipo: 'Tipo',
      multa: 'Multa',
      dano: 'Daño',
      retraso: 'Retraso',
      descripcion: 'Descripcion',
      montoOpcional: 'Monto (opcional)',
      agregar: 'Agregar',
      sinIncidentes: 'Sin incidentes registrados.',
      errorIncidente: 'Agrega una descripcion del incidente.',
      successIncidente: 'Incidente agregado al historial.',
    },
    notificacionesHu: {
      title: 'Centro de Notificaciones',
      subtitle: 'Historial de emails enviados a clientes',
      totalEnviados: 'Total Enviados',
      exitosos: 'Exitosos',
      fallidos: 'Fallidos',
      tasaExito: 'Tasa de Exito',
      plantillas: 'Plantillas personalizables',
      tipo: 'Tipo',
      confirmacion: 'Confirmacion',
      recordatorio: 'Recordatorio',
      mora: 'Mora',
      asunto: 'Asunto',
      mensaje: 'Mensaje',
      guardarPlantilla: 'Guardar plantilla',
      auto24h: 'Recordatorios automaticos (24h)',
      confirmadasDetectadas: 'Reservas confirmadas detectadas',
      colaProgramada: 'Cola programada',
      pendientes: 'pendientes',
      programar: 'Programar recordatorios',
      procesar: 'Procesar cola',
      tablaCaption: 'Historial de notificaciones enviadas',
      destinatario: 'Destinatario',
      fecha: 'Fecha',
      estado: 'Estado',
      successTemplate: 'Plantilla actualizada.',
      successProgramadas: 'recordatorios programados.',
      noProgramadas: 'No hay recordatorios nuevos por programar.',
      successEnviados: 'recordatorios enviados.',
      noEnviados: 'No hay recordatorios para enviar aun.',
      emailEnviado: 'Email enviado a',
      asuntoConfirmacionDefault: 'Confirmacion de Reserva #',
      mensajeConfirmacionDefault: 'Tu reserva ha sido confirmada para el vehiculo',
      asuntoCancelacionDefault: 'Cancelacion de Reserva #',
      mensajeCancelacionDefault: 'Tu reserva ha sido cancelada segun tu solicitud. El reembolso se procesara en 3-5 dias habiles.',
      asuntoReciboDefault: 'Recibo de Pago - Reserva #',
      mensajeReciboDefault: 'Gracias por tu preferencia. El monto total de',
      mensajeReciboProcesado: 'ha sido procesado exitosamente.',
    },
    reportesHu: {
      title: 'Reportes',
      subtitle: 'Facturacion exportable para auditoria contable',
      fechaInicial: 'Fecha inicial',
      fechaFinal: 'Fecha final',
      metodoPago: 'Metodo de pago',
      todos: 'Todos',
      exportarPdf: 'Exportar PDF',
      totalReservas: 'Reservas incluidas',
      totalFacturado: 'Total facturado',
      transacciones: 'Transacciones',
      subtotal: 'Subtotal',
      impuestos: 'Impuestos estimados',
      resumenMetodo: 'Resumen por metodo de pago',
      sinTransacciones: 'No hay transacciones para el filtro seleccionado.',
      tablaCaption: 'Reporte de reservas y facturacion',
      reserva: 'Reserva',
      cliente: 'Cliente',
      periodo: 'Periodo',
      metodoPagoCol: 'Metodo de Pago',
      estado: 'Estado',
      monto: 'Monto',
      sinResultados: 'No hay resultados para los filtros seleccionados.',
      agenciaDemo: 'RentOS Agencia Demo',
      ariaExportar: 'Exportar reporte a PDF',
    },
    tenantsHu: {
      title: 'Gestion de Tenants',
      subtitle: 'Panel de Super Admin - RentOS',
      nuevaAgencia: '+ Nueva Agencia',
      tenantActivoTitle: 'Tenant activo para operacion',
      tenantNoSeleccionado: 'No seleccionado',
      tenantActivoDesc: 'El limite de flota se valida usando este tenant al crear vehiculos.',
      totalAgencias: 'Total Agencias',
      activas: 'Activas',
      enPrueba: 'En Prueba',
      mrrTotal: 'MRR Total',
      nuevasMes: 'Nuevas Este Mes',
      tablaCaption: 'Lista de agencias suscritas',
      agencia: 'Agencia',
      plan: 'Plan',
      estado: 'Estado',
      flotaUso: 'Flota (Uso / Limite)',
      suscripcion: 'Suscripcion',
      acciones: 'Acciones',
      ilimitado: 'Ilimitado',
      activar: 'Activar',
      suspender: 'Suspender',
      editar: 'Editar',
      activo: 'Activo',
      seleccionar: 'Seleccionar',
      modalEditar: 'Editar Agencia',
      modalNueva: 'Nueva Agencia',
      nombreAgencia: 'Nombre de la Agencia',
      emailAdmin: 'Email del Administrador',
      pais: 'Pais',
      ciudad: 'Ciudad',
      limite: 'Limite maximo de vehiculos',
      fechaSuscripcion: 'Fecha de suscripcion',
      cancelar: 'Cancelar',
      guardarCambios: 'Guardar Cambios',
      crearTenant: 'Crear Tenant',
      successTenantActualizado: 'Tenant actualizado exitosamente',
      successTenantCreado: 'Tenant creado exitosamente',
      successTenantActivado: 'Tenant activado',
      successTenantSuspendido: 'Tenant suspendido',
      successTenantSeleccionado: 'seleccionado',
    },
    vehiculosHu: {
      tenantActivoPrefix: 'Tenant activo',
      flota: 'Flota',
      ilimitado: 'Ilimitado',
      addVehiculo: 'Añadir Vehículo',
      errorSeleccionTenant: 'Selecciona un tenant activo desde Super Admin antes de agregar vehículos.',
      limite: 'Limite',
      costoRenta: 'Costo de Renta',
      placa: 'Placa',
      recorrido: 'Recorrido',
      anio: 'Año',
      tipo: 'Tipo',
      editarFicha: 'Editar Ficha Tecnica',
      cerrar: 'Cerrar',
      mantenimiento: 'Mantenimiento',
    }
  },
  en: {
    nav: { 
      dashboard: 'Dashboard',
      vehiculos: 'Vehicles', 
      reservas: 'Bookings', 
      clientes: 'Clients', 
      reportes: 'Reports', 
      taller: 'Workshop', 
      tarifas: 'Rates',
      calendario: 'Calendar',
      notificaciones: 'Notifications',
      asistente: 'AI Assistant',
      superadmin: 'Super Admin'
    },
    header: { search: 'Search plate...', ticket: 'OPEN NEW TICKET' },
    home: { title: 'Fleet Management', subtitle: 'Inventory control and administration' },
    card: { km: 'Mileage', maint: 'Maintenance', btn_details: 'Details' },
    status: { available: 'Available', maintenance: 'In Shop', rented: 'Rented' },
    a11y: { dark: 'Dark Mode 🌙', light: 'Light Mode ☀️' },
    analytics: {
      title: 'Analytics Dashboard',
      subtitle: 'ROI, occupancy and fleet performance',
      ingresosMes: 'Monthly revenue',
      ingresosMesAnterior: 'Previous month revenue',
      roi: 'Estimated ROI',
      roiHelper: 'Estimated over fleet investment',
      ocupacion: 'Fleet occupancy',
      ocupacionHelper: 'vehicles total',
      clientesRegistrados: 'Registered clients',
      ingresos12m: 'Monthly revenue (12 months)',
      ingresosChartAria: 'Bar chart with monthly revenue for the last twelve months',
      estadoFlota: 'Fleet status',
      estadoFlotaChartAria: 'Pie chart with fleet status distribution',
      estadoFlotaHelper: 'Distribution between available, rented and maintenance',
      topRentables: 'Top profitable vehicles',
      gananciaEstimada: 'estimated profit',
    },
    assistantIA: {
      title: 'Fleet AI Assistant',
      subtitle: 'Smart recommendations for your business',
      demoMode: 'Demo Mode - AI connected in Cycle 2',
      quickBuy: 'Which motorcycle should I buy?',
      quickMaint: 'When should I do maintenance?',
      quickPrices: 'Analyze my pricing',
      quickRates: 'Rate strategy',
      emptyHello: 'Hi! I am your AI assistant.',
      emptyHint: 'Ask me about your fleet, maintenance, or pricing strategies.',
      placeholder: 'Type your question here...',
      send: 'Send',
      respComprar: 'Based on your current fleet analysis, I recommend acquiring Adventure or Naked motorcycles, as they have the highest occupancy rate (85%). Consider models like the BMW G310 GS or Yamaha MT-03, which are popular with your clients and have low maintenance costs.',
      respAdquirir: 'To expand your fleet, I suggest focusing on mid-range vehicles (price $45-60/day). These have the best balance between demand and profitability according to your historical data.',
      respMantenimiento: 'According to your fleet average mileage (12,500 km), I recommend preventive maintenance every 2,500 km. You currently have 2 vehicles close to the limit that should enter the workshop in the next 7 days.',
      respPrecio: 'Analyzing your current 65% occupancy, I suggest increasing prices by 15% on weekends and keeping 10% discounts for rentals longer than 7 days. This could increase your monthly revenue by approximately $2,400.',
      respTarifa: 'Your current rate strategy is solid. However, you could implement dynamic pricing for peak season (December-January and Holy Week) with 25-30% increases. This is common in the Colombian market.',
      respDefault: 'I have analyzed your business data. Your fleet has a 65% occupancy rate, with average income of $8,500/month. Naked-type vehicles are the most profitable. Would you like me to dive deeper into a specific aspect such as expansion, maintenance, or pricing strategy?',
    },
    reservas: {
      title: 'Booking Engine',
      subtitle: 'Availability and billing management',
      checkinShortcut: 'Check-in / Check-out',
      periodoTitle: '1. Rental Period',
      fechaRetiro: 'Pickup date',
      fechaDevolucion: 'Return date',
      diasTotales: 'Total days',
      tarifasTitle: '2. Rates and Add-ons',
      precioPorDia: 'Daily price',
      precioFijo: 'Fixed price',
      sinTarifas: 'No extra rates configured',
      crearCargo: 'Create New Charge',
      nombre: 'Name',
      cobrarPorDia: 'Charge per day',
      agregar: 'Add +',
      vehiculosDisponibles: 'Available Vehicles',
      rango: 'Range',
      sinDisponibilidad: 'No availability for these dates',
      sinDisponibilidadHint: 'Try changing dates or check maintenance status.',
      seleccionada: 'Selected',
      confirmarRenta: 'Confirm Rental',
      ticketReserva: 'Booking Ticket',
      periodo: 'Period',
      buscarCliente: 'Search client',
      buscarClientePlaceholder: 'Name or document',
      clienteSistema: 'System client',
      seleccionarCliente: 'Select client',
      licencia: 'License',
      vencimiento: 'Expiration',
      licenciaValida: 'Valid license for booking',
      licenciaInvalida: 'Expired or invalid license for selected date',
      metodoPago: 'Payment method',
      efectivo: 'Cash',
      tarjetaCredito: 'Credit card',
      tarjetaDebito: 'Debit card',
      transferencia: 'Bank transfer',
      billetera: 'Digital wallet',
      concepto: 'Concept',
      subtotal: 'Subtotal',
      rentaXDias: 'Rental x days',
      deposito: 'Required deposit',
      totalPagar: 'Total to pay',
      cancelar: 'Cancel',
      confirmarReserva: 'Confirm booking',
      errorSeleccionVehiculo: 'Select a vehicle to continue.',
      errorSeleccionCliente: 'Select an existing client to create booking.',
      errorLicencia: 'Client license is not valid for start date.',
      errorSolapamiento: 'Vehicle already has a booking in that range.',
      successReserva: 'Booking created successfully.',
    },
    calendarioHu: {
      title: 'Occupancy Calendar',
      subtitle: 'Weekly view to coordinate pickups and returns',
      nuevaReserva: '+ New booking',
      tipo: 'Type',
      estado: 'Status',
      todos: 'All',
      disponible: 'Available',
      rentado: 'Rented',
      mantenimiento: 'Maintenance',
      semanaAnterior: 'Previous week',
      semanaSiguiente: 'Next week',
      vehiculo: 'Vehicle',
      sinReservas: 'No bookings',
      libre: 'Free',
      sinVehiculos: 'No vehicles for those filters.',
      detalleLabel: 'Occupancy detail',
      detalleTitle: 'Occupancy detail',
      cerrar: 'Close',
      documento: 'Document',
      periodo: 'Period',
    },
    checkin: {
      title: 'Check-in / Check-out',
      subtitle: 'Physical vehicle condition log',
      volverReservas: 'Back to bookings',
      reserva: 'Booking',
      seleccionar: 'Select',
      tipoRegistro: 'Record type',
      vehiculo: 'Vehicle',
      sinSeleccionar: 'Not selected',
      kilometraje: 'Mileage',
      combustible: 'Fuel (%)',
      checklist: 'Condition checklist',
      fotos: 'Photos (comma-separated URLs)',
      observaciones: 'Notes',
      guardar: 'Save',
      historial: 'Inspection history',
      sinInspecciones: 'No inspections recorded yet.',
      errorReserva: 'Select a valid booking to continue.',
      successGuardado: 'Record saved successfully.',
      errorGuardado: 'Could not save inspection.',
      kmAbbr: 'KM',
      combustibleAbbr: 'Fuel',
    },
    clientesHu: {
      title: 'Client Database',
      subtitle: 'Profile and information management',
      nuevo: '+ New Client',
      buscarPlaceholder: 'Search by name, document, phone or email...',
      tablaCaption: 'Registered client list',
      cliente: 'Client',
      documento: 'Document',
      contacto: 'Contact',
      reservas: 'Bookings',
      score: 'Score',
      clasificacion: 'Classification',
      acciones: 'Actions',
      ver: 'View',
      editar: 'Edit',
      modalEditar: 'Edit Client',
      modalNuevo: 'New Client',
      nombreCompleto: 'Full Name',
      email: 'Email',
      tipoDocumento: 'Document Type',
      numeroDocumento: 'Document Number',
      telefono: 'Phone',
      fechaNacimiento: 'Birth Date',
      direccion: 'Address',
      licenciaNumero: 'License Number',
      categoria: 'Category',
      vencimiento: 'Expiration',
      cancelar: 'Cancel',
      actualizar: 'Update',
      crear: 'Create',
      successActualizado: 'Client updated successfully',
      successCreado: 'Client created successfully',
      errorGuardar: 'Could not save client',
      frecuente: 'FREQUENT',
      riesgo: 'RISK',
      nuevoLabel: 'NEW',
      regular: 'REGULAR',
    },
    clienteDetalle: {
      notFound: 'Client not found',
      volverListado: 'Back to list',
      ficha: 'Client File',
      volver: 'Back',
      riesgoTitle: 'High risk detected',
      riesgoDesc: 'Client has recent incidents/fines. Review conditions before confirming new booking.',
      ltv: 'LTV',
      reservasTotales: 'Total bookings',
      reservasActivas: 'Active bookings',
      multasDanos: 'Fines/Damages',
      topVehiculos: 'Most rented vehicles',
      sinHistorico: 'No booking history available.',
      incidentesTitle: 'Incidents and fines',
      tipo: 'Type',
      multa: 'Fine',
      dano: 'Damage',
      retraso: 'Delay',
      descripcion: 'Description',
      montoOpcional: 'Amount (optional)',
      agregar: 'Add',
      sinIncidentes: 'No incidents registered.',
      errorIncidente: 'Add an incident description.',
      successIncidente: 'Incident added to history.',
    },
    notificacionesHu: {
      title: 'Notification Center',
      subtitle: 'History of emails sent to clients',
      totalEnviados: 'Total sent',
      exitosos: 'Successful',
      fallidos: 'Failed',
      tasaExito: 'Success rate',
      plantillas: 'Custom templates',
      tipo: 'Type',
      confirmacion: 'Confirmation',
      recordatorio: 'Reminder',
      mora: 'Overdue',
      asunto: 'Subject',
      mensaje: 'Message',
      guardarPlantilla: 'Save template',
      auto24h: 'Automatic reminders (24h)',
      confirmadasDetectadas: 'Confirmed bookings detected',
      colaProgramada: 'Scheduled queue',
      pendientes: 'pending',
      programar: 'Schedule reminders',
      procesar: 'Process queue',
      tablaCaption: 'Sent notification history',
      destinatario: 'Recipient',
      fecha: 'Date',
      estado: 'Status',
      successTemplate: 'Template updated.',
      successProgramadas: 'reminders scheduled.',
      noProgramadas: 'No new reminders to schedule.',
      successEnviados: 'reminders sent.',
      noEnviados: 'No reminders to send yet.',
      emailEnviado: 'Email sent to',
      asuntoConfirmacionDefault: 'Booking Confirmation #',
      mensajeConfirmacionDefault: 'Your booking has been confirmed for vehicle',
      asuntoCancelacionDefault: 'Booking Cancellation #',
      mensajeCancelacionDefault: 'Your booking has been cancelled as requested. Refund will be processed in 3-5 business days.',
      asuntoReciboDefault: 'Payment Receipt - Booking #',
      mensajeReciboDefault: 'Thanks for your preference. The total amount of',
      mensajeReciboProcesado: 'has been processed successfully.',
    },
    reportesHu: {
      title: 'Reports',
      subtitle: 'Exportable billing for accounting audits',
      fechaInicial: 'Start date',
      fechaFinal: 'End date',
      metodoPago: 'Payment method',
      todos: 'All',
      exportarPdf: 'Export PDF',
      totalReservas: 'Included bookings',
      totalFacturado: 'Total billed',
      transacciones: 'Transactions',
      subtotal: 'Subtotal',
      impuestos: 'Estimated taxes',
      resumenMetodo: 'Summary by payment method',
      sinTransacciones: 'No transactions for selected filters.',
      tablaCaption: 'Bookings and billing report',
      reserva: 'Booking',
      cliente: 'Client',
      periodo: 'Period',
      metodoPagoCol: 'Payment method',
      estado: 'Status',
      monto: 'Amount',
      sinResultados: 'No results for selected filters.',
      agenciaDemo: 'RentOS Demo Agency',
      ariaExportar: 'Export report to PDF',
    },
    tenantsHu: {
      title: 'Tenant Management',
      subtitle: 'RentOS Super Admin panel',
      nuevaAgencia: '+ New Agency',
      tenantActivoTitle: 'Active tenant for operations',
      tenantNoSeleccionado: 'Not selected',
      tenantActivoDesc: 'Fleet limit validations use this tenant when creating vehicles.',
      totalAgencias: 'Total agencies',
      activas: 'Active',
      enPrueba: 'Trial',
      mrrTotal: 'Total MRR',
      nuevasMes: 'New this month',
      tablaCaption: 'Subscribed agencies list',
      agencia: 'Agency',
      plan: 'Plan',
      estado: 'Status',
      flotaUso: 'Fleet (Used / Limit)',
      suscripcion: 'Subscription',
      acciones: 'Actions',
      ilimitado: 'Unlimited',
      activar: 'Activate',
      suspender: 'Suspend',
      editar: 'Edit',
      activo: 'Active',
      seleccionar: 'Select',
      modalEditar: 'Edit Agency',
      modalNueva: 'New Agency',
      nombreAgencia: 'Agency Name',
      emailAdmin: 'Admin Email',
      pais: 'Country',
      ciudad: 'City',
      limite: 'Max vehicle limit',
      fechaSuscripcion: 'Subscription date',
      cancelar: 'Cancel',
      guardarCambios: 'Save Changes',
      crearTenant: 'Create Tenant',
      successTenantActualizado: 'Tenant updated successfully',
      successTenantCreado: 'Tenant created successfully',
      successTenantActivado: 'Tenant activated',
      successTenantSuspendido: 'Tenant suspended',
      successTenantSeleccionado: 'selected',
    },
    vehiculosHu: {
      tenantActivoPrefix: 'Active tenant',
      flota: 'Fleet',
      ilimitado: 'Unlimited',
      addVehiculo: 'Add Vehicle',
      errorSeleccionTenant: 'Select an active tenant from Super Admin before adding vehicles.',
      limite: 'Limit',
      costoRenta: 'Rental Cost',
      placa: 'Plate',
      recorrido: 'Mileage',
      anio: 'Year',
      tipo: 'Type',
      editarFicha: 'Edit Spec Sheet',
      cerrar: 'Close',
      mantenimiento: 'Maintenance',
    }
  }
};

const defaultConfig = {
  lang: 'es' as 'es' | 'en',
  highContrast: false,
  t: (section: string, key: string) => {
    // @ts-ignore
    return dictionary.es[section]?.[key] || key;
  },
  toggleLang: () => {},
  toggleContrast: () => {},
};

const ConfigContext = createContext<any>(defaultConfig);

export const ConfigProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<'es' | 'en'>('es');
  const [highContrast, setHighContrast] = useState(false);

  const t = (section: string, key: string) => {
    // @ts-ignore
    return dictionary[lang][section]?.[key] || key;
  };

  return (
    <ConfigContext.Provider value={{ 
      lang, 
      highContrast, 
      t,
      toggleLang: () => setLang(l => l === 'es' ? 'en' : 'es'),
      toggleContrast: () => setHighContrast(c => !c)
    }}>
      {children}
    </ConfigContext.Provider>
  );
};

export const useConfig = () => useContext(ConfigContext);